name: Bug Report
description: "hello"
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
 
